# # საშუალო
# def საშუალო(a, b):
#     print((a + b)/2)


# საშუალო(100, 50)



#გამრავლება
def გამრავლება(a, b):
     while len("a") < b:
         len("a") + 1
         a += 1 
     if len("a") == b:
         print(a)
გამრავლება(10, 10)

# გამრავლება(10, 2)

# გაყოფა
''' i = 0
def გაყოფა(a, b):
    while i * b < a:
        0 + 0.000001
        if i * b == a:
            print(i)
გაყოფა(10, 2)
 '''

''' hello'''

# XDFV5ZGTU7N8 Y6IB9-MOP0,/\    print("your price is"), foodprice(food, type2, foodsprice, quantity, typesprice), print("dollar") # fasis gageba
